### ISSUE TITLE
海外模式又不行了。

### ISSUE THREAD

**Issue by happlebao** [EraserKing/Unblock163MusicClient#3]
专辑链接：http://music.163.com/#/album?id=71074
歌名：【only my railgun - (TV动画《科学超电磁炮》片头曲)MV】

网页版可用。获得的地址是
```
http://219.138.27.56/m2.music.126.net/tub39VQVu455UARPXJlj0g==/3402988488666004.mp3
```

win下客户端
```
Song ID = 725692, DFS ID = 3338117303174788
Song URL = http://p2.music.126.net/stNhURpEJCgM0SiLf9M2ng==/3338117303174788.mp3
```
地址不一样啊。。。
win 下网易客户端报【加载失败】。
![error](http://i.imgur.com/gmjhs5s.png)
win 下的地址复制到浏览器是 nginx 的 403 Forbidden 错误。而网页版的地址复制到浏览器可用。

坐标：爱尔兰
系统：win10

**Comment by SergioZgz** [comment]
Yes... this is because m2 is china subdomain and p3 is overseas one... and Netease is blocking songs from overseas (1 day ago start this nightmare)... you could get the correct url with new eapi... and the requests looks like:

POST http://music.163.com/eapi/song/enhance/player/url HTTP/1.1
Host: music.163.com
Connection: keep-alive
Content-Length: 842
Accept: */*
Content-Type: application/x-www-form-urlencoded
Origin: orpheus://orpheus
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.157 Safari/537.36
Accept-Encoding: gzip,deflate
Accept-Language: en-us,en;q=0.8
Cookie: os=pc; deviceId=0D7565F24D1B6DD5CF2393389C51317871EB96D408606E511A6B; osver=Microsoft-Windows-10-Professional-build-10586-64bit; appver=1.9.4.120103; MUSIC_A=7d4ec7972d0cacaf6dbd93da53dd044ce8571b7f8bc22191667c06c8151ce3130dc3bf4fcae825f88cbf918d23b9697bac5f4bb14a0a4c5aa21e42b4d96a9e941667129ec9bd61d15bde884923b7e1446a6a470a268b23d02c1c1aed05a82c5fc3061cd18d77b7a0; __csrf=a0ded93d78ec2955698ad3cd1f1257b7; channel=netease

params=FA90B329E9614F79E79598F37DC2EDB430F8378D2A2796338F0BFDEAEF824A22975CDA9D96D79E6DC4A59218CDB8199F0634C7CC57DB74580AC841C7D4E3AD7E4C5CFB39749A72F162C64AEBD2BDFD356938AD9B38E451B678561419F8D0E324462EE3AF676D09A9087B13263A9C7EBC8234DD08180F5DD981BF79C4AD134609FBEBC1752DB0BA90405C963B87B3F26476D4C3FA2A926F43C080D9E561FEF17447FC8528FA3EE03BD74720EDE086548A57E9A703CF1B10241910870265A8DC9D3DC464E6D7A9940D2A020BF4B758D815DBCB71DE5376D4ADB8DA8F672E6BB94C94ED5D573C2DC0318D9D9215EB830B04855E751EFF0F8E9A13CC189AD3B7F54D5A38F1112CEDFEC0040447559DAEEF553C0E6CE723889EF94B58B8331CCAB52D2F04ECC0008B0CB4BC1BBBAEE6C5A1430F5246AD1E18EEF406BC3177072B10D7A743B2B068AA3B7158FC78A52A9A6FC4AD1D1B439E14AE1F3C312AEE72E7CC49406FC005856E838FBF3B9CB303324EB26136A1B8A644E0C9234F7D0B59DF90C61C0F31530E4EDA65E4EBA3FC4C3029850E40FA21DA4FC31DBDB565E2BEB66E9F%00


This means that the params are cypher (maybe with RSA like login)

But by the way what the hell is http://219.138.27.56 ??? I tried all urls that doesnt work since yesterday (all p3 and p4 songs that previously works) and with that """proxy""" works correctly... is this a public proxy? is a yours? what is this????

**Comment by EraserKing** [comment]
在论坛上看到了一些评论 同样是海外用户报的问题 国内用户似乎没有问题
p*原来是网易提供的一组针对海外的服务器 然而现在无法使用
现在新的方式是修改URL添加219.138.27.56在前面
这些（以及其它的一些）是网易的反向代理 并不是我提供的
我会升级一下以适应这个改动
(params是加密的，不过我并不关心它的内容)

-----

English version:
I've seen some comments and they're reported by users overseas. The domestic users didn't run into this issue.
The server p* are provided for overseas users but they aren't working now.
The new way is to modify the returned URL to add 219.138.27.56 at the beginning.
This (plus some more) are reverse proxy by Netease, but not mine.
I wil update to fix this.
(params is encrypted, nevertheless I don't care about its content)

**Comment by SergioZgz** [comment]
Thanks :) do you have others proxies like that???

**Comment by EraserKing** [comment]
Please upgrade to 0.5 version and you can assign a proxy by `/overseasproxy` parameter.
You could pick one as you like. The list is in `README.md`.

**Comment by SergioZgz** [comment]
:)
